### ISSUE TITLE
не соответствие макету

### ISSUE THREAD

**Issue by Geksanit** [prodderman/FlatUI#14]
Ui-Kit - далёк от макета. Добавь в репозиторий изображение для проверки в PerfectPixel.  У полей формы нет отображения errror/thanks, в user profile нет кртинок (соц бар), и остальное по мелочи.

**Comment by Geksanit** [comment]
Из всего перечисленного пока только соц бар сделан, а остальное ? :)

**Comment by prodderman** [comment]
То есть у формы должны сразу отображаться error/thanks? они отображаются при сабмите

**Comment by Geksanit** [comment]
Ок, но почему-то только error отображается при сабмите.

**Comment by prodderman** [comment]
Потому что поля name и email обязательные 
![image](https://user-images.githubusercontent.com/24736776/38454736-b82c4e12-3a96-11e8-8706-61adb807a592.png)
