### ISSUE TITLE
не соответсвие БЭМу

### ISSUE THREAD

**Issue by Geksanit** [prodderman/FlatUI#15]
Есть блок `.btn` но лежит он не в `btn.pug`. По бэму название блока должно соответствовать имени файла и папки. Это позволяет легко находить блоки. Для имени блока `.button` подходит лучше чем `.btn`

**Comment by Geksanit** [comment]
`_red` по бэму это выглядит как булев модификатор (как будто других цветов нет и не будет), тут правильней использовать модификатор `_ключ_значение`. И такое почти во всех блоках )

**Comment by Geksanit** [comment]
странно, я намекал на _color_red.

**Comment by prodderman** [comment]
я понимаю, просто других цветов больше не предполагалось, поэтому сделал второй цвет альтернативным

**Comment by Geksanit** [comment]
![image](https://user-images.githubusercontent.com/31949379/38866049-e1ef4b0c-4269-11e8-85c3-c2e89539adad.png)
-------------------------
![image](https://user-images.githubusercontent.com/31949379/38866182-3e7e9eea-426a-11e8-92b4-d472c25e0adc.png)
Что тут не правильно:
1. использовать миксина для элемента вне блока,
2. название миксина не соответствует классу. 
3. использование микса.

**Comment by prodderman** [comment]
в вашем [примере](https://github.com/fullstack-development/flat-starter-kit/blob/master/src/pages/messages/messages.pug) активно используются миксы, или там лучше не смотреть?
