### ISSUE TITLE
Мелкие правки

### ISSUE THREAD

**Issue by Geksanit** [prodderman/FlatUI#16]
1. Поправь стиль кода в pug файлах: пробелы до и после знака равно, в литерале обьекта и т.д. - как в js.
2. Добавь в кастомные страницы кастомизацию новостей и ивентов (текст, картинка, цвет), а то они все одинаковые 0_о.
3. В arrow.styl есть селектор тега, а по тегам селектить не нужно.
4. в компоненте singin - правильней sign in, а не sing in.

**Comment by chmnkh** [comment]
5. В блоке messenger на кнопке должно быть reply написано, а не replay :)
