### ISSUE TITLE
Стили блока

### ISSUE THREAD

**Issue by chmnkh** [prodderman/FlatUI#19]
Что у тебя в файле со стилями для блока slider делают стили для рутового элемента?
```
:root
  --slider-color $c_green

.slider
  flex 1 1 auto
```

**Comment by chmnkh** [comment]
```
&.messenger-resizable
&.messenger-draggable
    position fixed
    bottom 0
    left 6.25rem
    box-shadow 0 0 0.438rem 0 rgba(0,0,0,0.4)
```
Фактически, у тебя стили блока messenger содержат стили блоков (кстати, почему блоков?) messenger-resizable и messenger-draggable

**Comment by chmnkh** [comment]
А селектор такой сложный почему оставил? Если можно написать проще - пиши проще: это и потом легче понять будет (не надо будет со специфичностью бороться), и не будут возникать мысли типа "зачем же тут специфичность повысили".

**Comment by prodderman** [comment]
это что бы повысить специфичность селектора и переопределить стили плагина.
