### ISSUE TITLE
global.styl

### ISSUE THREAD

**Issue by kinda-neat** [prodderman/FlatUI#3]
Вот так задавать стили глобально как у тебя сейчас в global.styl, говорит как раз о не самодостаточности блока если в нем есть тот же h1, h2, button и т.д.
Нужно разнести все по блокам, за исключением шрифтов и стилей ниже
![2018-02-04 10-41-14](https://user-images.githubusercontent.com/27883524/35774082-f40057ce-0997-11e8-9f35-e365d00e8ed5.png)
И все что ты задал в body лучше перенеси в html
!Прописывать дефолтный цвет фона, цвет шрифта, font-size и семейство шрифта у html 
Здесь же, vars.styl переименовать в colors.styl

**Comment by prodderman** [comment]
в вашем [примере](https://github.com/fullstack-development/flat-starter-kit/blob/master/src/theme/global.scss#L26) касательно заголовков  сделано так же, или там не правильно?

**Comment by kinda-neat** [comment]
Да, там не правильно, но тебе нужно сделать правильно

**Comment by prodderman** [comment]
то есть лучше сделать заголовки отдельным блоком?

**Comment by Geksanit** [comment]
осталось  vars.styl переименовать в colors.styl и можно будет закрывать ишью

**Comment by prodderman** [comment]
предполагалось, что будут и другие переменные кроме цветов
