### ISSUE TITLE
Переработать блок layout

### ISSUE THREAD

**Issue by chmnkh** [prodderman/FlatUI#31]
Создал отдельное ишью, чтобы было удобнее проверять. Во-первых см. комменты по-поводу этого блока в  #23. Далее: не нужно использовать модификаторы по типу Atomic css :) Ты все очень усложнил, повыпиливай все эти модификаторы, добавь новые и более осмысленные по необходимости.

**Comment by chmnkh** [comment]
https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_8av0l/
Изучи еще раз про модификаторы.
Если что-то не понятно, задавай вопросы.

**Comment by Geksanit** [comment]
проверить неиспользуемые классы и можно закрывать
