### ISSUE TITLE
Именование ФВП

### ISSUE THREAD

**Issue by chmnkh** [prodderman/FlatUI#48]
https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_8av0m/
Изучи второй пункт (про ФВП) и исправь везде у себя.
Пример неправильного именования: 
```
goToMarker(map, marker) {
  return function() {
      map.panTo(marker.geometry.getCoordinates());
  };
}
```

**Comment by Geksanit** [comment]
можно закрывать
